version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  publish:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo make dev-install
      - run: pip install setuptools wheel twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u $USERNAME -p $PASSWORD dist/*
      - slack/status
  test-dev-tag-as-not-passed:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    steps:
      - checkout
      - run: (cd .circleci/ && ./markDevTagAsTestNotPassed.sh)
  test-unit:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./doUnitTests.sh)
      - slack/status
  test-website-fastapi:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./websiteFastApi.sh)
      - slack/status
  test-website-flask:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./websiteFlask.sh)
      - slack/status
  test-website-django:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./websiteDjango.sh)
      - slack/status
  test-authreact-fastapi:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./authReactFastApi.sh)
      - slack/status
  test-authreact-flask:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./authReactFlask.sh)
      - slack/status
  test-authreact-django:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    resource_class: large
    steps:
      - checkout
      - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
      - run: make dev-install
      - run: (cd .circleci/ && ./authReactDjango.sh)
      - slack/status
  test-success:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    steps:
      - checkout
      - run: (cd .circleci/ && ./markAsSuccess.sh)
      - slack/status
  update-docs:
    docker:
      - image: rishabhpoddar/supertokens_website_sdk_testing
    steps:
      - checkout
      - run: cd ../ && git clone git@github.com:supertokens/supertokens-backend-website.git
      - run: (cd .circleci && ./updateDocsInWebsite.sh)
      - slack/status

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          context:
            - slack-notification
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-dev-tag-as-not-passed:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-unit:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-website-fastapi:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-website-flask:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-website-django:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-authreact-fastapi:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-authreact-flask:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-authreact-django:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-success:
          requires:
            - test-unit
            - test-website-fastapi
            - test-website-flask
            - test-website-django
            - test-authreact-fastapi
            - test-authreact-flask
            - test-authreact-django
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - update-docs:
          context:
            - slack-notification
          filters:
            branches:
              only:
                - master